name: thesis_project

channels:
  - defaults
  - conda-forge
  - opensourceeconomics
  - janosg

dependencies:
  - python

  - pandas
  - numpy
  - scipy
  - numba
  - respy
  - estimagic>=0.0.14
  - chaospy

  - pip
  - ipykernel
  - jupyterlab
  - pytest
  - pytest-cov
  - black
  - flake8
  - doc8

  - pip:
    - matplotlib
    - seaborn
    - salib
    - openturns
    - pre-commit
    - codecov

    - black-nb
    - flake8-nb
